### ISSUE TITLE
[BUG] Install Error: "Certificate doesn't match publisher" on Windows Server SP2 MSIXMgr

### ISSUE THREAD

**Issue by mjfusa** [microsoft/msix-packaging#342]
*Project*
Win7Msix / MSIXMgr

**Describe the bug**
Install Error: "Certificate doesn't match publisher" if an ampersand is in Certificate Subject name and in manifest publisher name.

**To Reproduce**
1) Create an MSIX package that is signed with a certificate subject and manifest publisher name with an ampersand. Note: signtool / VS/ MSIX Packaging Manager can sign the app without problems.
2) Install the app on Windows 10. Any version >= 1709.
3) Install the app using MSIXManager on Windows Server SP2.

**Expected behavior**
App installs without errors on Windows 10.
App installs without errors on Windows Server SP2.

**Actual behavior**
App installs without errors on Windows 10.
App installs with error that indicates a mismatch between the signing cert and publisher name in the app package.

**Screenshots**
NA

**Platform**
Windows 10. Any version >= 1709.
Windows Server SP2.

**Additional context**

**Comment by mjfusa** [comment]
Suggest label [AppConsult]

**Comment by mjfusa** [comment]
I did more digging in my issue with msixcore. Turns out, if I use a package created with Visual Studio packaging project, the package is installed successfully by msixmgr on a windows 7 machine (I do not know if the signing of the package by visual studio adds a timestamp).
If I create the package with makeappx and sign with  signtool (no timestamp) works also. If I sign the package with timestamp, it will fail (the error is misleading saying invalid publisher).
I also tried the preview bits, same thing.

**Comment by ksaunder** [comment]
My team just ran into what appears to be same issue today.  In attempting to install our msix application on Windows Server 2016 we were confronted by one of two errors as we tried different things.  Cannot open app package: Reason: 0x8bad0043 and Cannot open app package: Reason: 0x80070459.

Our publisher name in the identity tag of the AppManifest.xml file is:
<Identity ProcessorArchitecture="x86" Version="11.0.0.0" Publisher="CN=schneider electric industries sas, OU=Global Operations, O=schneider electric industries sas, L=RUEIL-MALMAISON, S=Île-de-France, C=FR" Name="AppName"/>
As can be seen there is a special French letter in the name.  

After finding this issue we tested with a self-signed code signing certificate and the issue went away and we could install the application.

As an organization we are required to use the code signing certificate provided by our main IT group and we have customers who need to install this application on Windows Server 2016 for a while still.  Having this issue resolved is really important for our adoption of MSIX.  We really like the features that it provides on the newer builds of Server and Windows 10 but this issue is causing a road block for us.

**Comment by dhoehna** [comment]
Is this issue only seen on Windows Server 2016?  From the initial comment it looks like the app can install fine on Windows 10, but fails on Windows Server 2016.

**Comment by mjfusa** [comment]
This was also reproed on Windows Server 2012 SP2.

**Comment by dhoehna** [comment]
I see, so, it may just be a windows server issue.  Coolio.
