### ISSUE TITLE
Deploy of MSIX Any CPU Project fails with MSIL error because of /platform:x86

### ISSUE THREAD

**Issue by mwmccallum** [microsoft/msix-packaging#386]
When trying to build an MSIX project with Any CPU selected, getting an MSIL "mismatch between the processor architecture" error. Each project in the MSIL solution has Any CPU defined in the Release. If I change to x64 or x86 specific, the project builds just fine. 

The csc.exe command has a /platform:x86 option on it when running AnyCPU. When I pick either x64 or x86 for builds, the platform setting is correct. It is only when picking AnyCPU that the platform is set incorrectly to /platform:x86.

I can build the solution without issue with AnyCPU. It is only when doing a Deploy and picking Neutral (Any CPU) that I see the incorrect /platform:x86 entry on the csc.exe line.

**Comment by jvintzel** [comment]
This looks to be an issue within Visual Studio.  Would it be possible for you to post here?  [https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019 )

**Comment by mwmccallum** [comment]
Thanks for the feedback, This issue happens only with MSIX projects using either msbuild or vsbuild. the associated projects in MSIX solution is getting built as x86 when AnyCPU is used but the MSIX project is trying to build as AnyCPU which gives the MSIL failure. That is why I thought it was specific to the MSIX project and/or template.

I will submit an issue to VS link you noted above.

Thanks, Mike

**Comment by DennisVM-D2i** [comment]
So annoying, I'm seeing this too.  All builds ok - including the main/host WinForms app, as 'Any CPU', but it's only when I try to 'Publish' the MSIX project, that I receive the MSIL <-> x86 error, and see that an 'x86' folder has been created/built for the main/host Winforms app, alongside the 'Debug' folder.

F.Y.I.  Due to the use of toast notifications - for both Win 10 and Win 11, I had to add these - not sure if it is related (?):

    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>

Anyone found an easy fix for this?
