### ISSUE TITLE
Migrate Microsoft.Msix.Utils library to .NET Standard/.NET Core

### ISSUE THREAD

**Issue by palenshus** [microsoft/msix-packaging#399]
Hi! We're consuming this library from our .NET Standard 2.1 project, and though it works fine, it gives us warnings at nuget restore time that are cluttering our build and also breaking the GitHub build action's "dotnet restore" phase.

Unless there are technical reasons this library can't be migrated, it'd be great if it could be updated. Thanks!

```
....csproj : warning NU1701: Package 'Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [....sln]
....csproj : warning NU1701: Package 'Microsoft.Msix.Utils 1.0.200918001' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [....sln]
  Failed to restore ....csproj (in 22.25 sec).
```

**Comment by lechacon** [comment]
Hi @palenshus . Sorry for the delay.

The library used to have a .NET Core version before it was moved to GitHub, and it was actually removed once it was here on #376 

As far as I remember, the only differences were [this line](https://github.com/microsoft/msix-packaging/blob/ce2415b3b085a7241dabaf1ce1cd7680cae7b7c2/tools/utils/UtilsNetCore/Logger/ConsoleLog.cs#L95) and the [ProcessRunner class](https://github.com/microsoft/msix-packaging/blob/ce2415b3b085a7241dabaf1ce1cd7680cae7b7c2/tools/utils/UtilsNetCore/ProcessRunner/NetCoreProcessRunner.cs) which used the Process class in .NETFramework and native methods in .NETCore. I believe the split was because it used to run in a limited CLR and there may not be any technical reason to not do it.

I'll try changing it and seeing if it causes any issues.

**Comment by samiranshah** [comment]
@palenshus The PR for this update has been merged, the package will be published soon.

**Comment by palenshus** [comment]
Beautiful, thank you!
