### ISSUE TITLE
Platform dependent package installation for UWP apps

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/msix-packaging#402]
I am working on an UWP app with desktop extension. I don't know if this is the right place to ask this, for platforms that doesn't support `fulltrust` api will the `fulltrust` component be installed??
If not then is there any way I can limit the installation of the `fulltrust` component so that it only installs on platforms that support it?? I have looked into something like optional packages and related sets, the desktop extension uses a combination of named pipes, memory-mapped files and local app data, does optional package support apps running in same process group having same local data??

**Comment by DrusTheAxe** [comment]
> I don't know if this is the right place to ask this

No such thing as a bad place if it leads to active conversation

For future reference [Project Reunion](https://github.com/microsoft/ProjectReunion/) is a good place for such potentially broad questions. At a minimum there's a lot of folks tracking that project so lots of active eyeballs :-)

> for platforms that doesn't support fulltrust api will the fulltrust component be installed??

That's not quite how it works. There is no 'partial package' installation. Packages declaring the runFullTrust capability won't install on platforms that don't support fulltrust. As packages declaring full trust functionality can't install without declaring the runFullTrust capability optional packages that need the fulltrust support won't install.

Unfortunately, splitting up your package isn't a workaround as capabilities can only be declared in a Main package today. Optional packages declaring full trust components rely on the associated Main package to declare the runFullTrust capability.

Thinking out loud...if you could declare capabilities in an Optional package it would let you accomplish your goal, but that would require changes to several places across the appmodel -- packaging APIs, the deployment pipeline (handling package install/update), capability plumbing to support the union of Main+Optional(+Framework+Resource) declared capabilities instead of the current just-the-Main `<Capabilities>`, various tools (e.g. makeappx.exe and VisualStudio) and probably more. It's an interesting thought. If this interests you please start an issue in the [Project Reunion](https://github.com/microsoft/ProjectReunion/) repository.

> limit the installation of the fulltrust component so that it only installs on platforms that support it??

Mayyyybe. It depends on your specifics. Can you provide more details?

If you're declaring a full trust component in your appxmanifest.xml **and the XML node has a platform-specific namespace** then that would only apply to the supporting platform. For instance, `<desktop6:Extension Category="windows.service"...>` is specific to desktop platforms (i.e. desktop+server) and not visible on other platforms (Xbox etc). Thus you can define this in your appxmanifest.xml and it'll be processed on desktop machines but effectively invisible and doesn't exist on Xbox or Hololens devices.

Most appxmanifest.xml declarations are in a uapN namespace which are available on all platforms (as of a the respective version) e.g. `<uap10:Extension Category="windows.hostRuntime"...>` is available on all devices (desktop, server, Xbox, Hololens, etc) as of [Windows 10 Version 2004](https://docs.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/what-s-changed-in-windows-10). Generally anything in uapN namespaces are universal and available on all platforms (as of the respective version). A subset of namespaces are platform-specific e.g. desktop3.

I have looked into something like optional packages and related sets, the desktop extension uses a combination of named pipes, memory-mapped files and local app data, 

> does optional package support apps running in same process group having same local data?

Yes. Processes per definitions in Optional packages run with the package identity of the associated Main package and thus same data.

You can think of Optional packages as a way to take a Main package and slice it up into a 'required' package and 1+ 'optional' packages. Users install the required/Main package and 0+ optional/Optional packages and then at runtime the Main and Optional(s) present act and are used as if they're part of 1 Main package all along. At runtime their processes have the same package identity so they have access to the same data resources, the same capabilities, etc. But I could have Main+Opt1+Opt2, you could have Main+Opt2+Opt3, someone else could have Main, someone else Main+Opt1+Opt2+Opt3+Opt4 etc

**Comment by soumyamahunt** [comment]
> No such thing as a bad place if it leads to active conversation :D

Thanks for understanding.
> That's not quite how it works. There is no 'partial package' installation.

Would be nice to add this as a feature where in packagelayout platform dependency can be declared for flat bundles, optional packages and related sets. Also, it would be much easier to declare platform dependencies in Packaging project file itself.
 >Packages declaring the runFullTrust capability won't install on platforms that don't support fulltrust. As packages declaring full trust functionality can't install without declaring the runFullTrust capability optional packages that need the fulltrust support won't install.

Is this only related to `runFullTrust` capability or any capability?? I have seen some people able to install apps with `broadFileSystemAccess` capability in Xbox even though Xbox doesn't support it. My understanding was capabilities behave the same as extensions, if the platform doesn't support it then they are just ignored instead of causing an installation failure. Am I misled regarding this??
> Mayyyybe. It depends on your specifics. Can you provide more details?

My project is set up the similar way [this](https://stefanwick.com/2018/04/06/uwp-with-desktop-extension-part-1/comment-page-1/#:~:text=Including%20a%20desktop%20extension%20%28%E2%80%98windows.fullTrustProcess%E2%80%99%29%20in%20your%20UWP,access%20to%20all%20public%20APIs%20on%20the%20machine.) sample describes adding desktop extension.
> Yes. Processes per definitions in Optional packages run with the package identity of the associated Main package and thus same data.
> 
> You can think of Optional packages as a way to take a Main package and slice it up into a 'required' package and 1+ 'optional' packages. Users install the required/Main package and 0+ optional/Optional packages and then at runtime the Main and Optional(s) present act and are used as if they're part of 1 Main package all along. At runtime their processes have the same package identity so they have access to the same data resources, the same capabilities, etc. But I could have Main+Opt1+Opt2, you could have Main+Opt2+Opt3, someone else could have Main, someone else Main+Opt1+Opt2+Opt3+Opt4 etc

Another thing I forgot to ask, are the optional packages installed in the same directory as the main package?? The requirement of adding desktop extension is to specify path to the .exe in manifest.  Since optional packages can be moved around independent of main package do I need to find other way of launching the desktop extension??

**Comment by anarvekar-msft** [comment]
Please feel free to reopen the issue if you believe the answer above didn't suffice. Closing this out.

**Comment by anarvekar-msft** [comment]
From @DrusTheAxe 

> Another thing I forgot to ask, are the optional packages installed in the same directory as the main package?? 
No. Every package is installed to its own unique directory.

> The requirement of adding desktop extension is to specify path to the .exe in manifest. 
Why?

> Since optional packages can be moved around independent of main package do I need to find other way of launching the desktop extension??

What is a "desktop extension"? If it's an application then it's got an ApplicationUserModelId (AUMID) so ApplicationActivateManager.ActivateApplication(aumid...) is the canonical way to directly launch an all. It's the moral equivalent (roughly) of CreateProcess(foo.exe), but more convenient since AUMIDs don't change based on where a package lives on the filesystem. When you click on a tile in Start Menu (for, say, Calculator) shell calls ActivateApplication.


If you still have this question, or if the above answers didn't suffice, please feel free to reopen the issue.
