### ISSUE TITLE
[BUG] MSIX Azure DevOps Extension fails if there is a space in build agent path

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/msix-packaging#410]
**Describe the bug**
When using the Azure DevOps MSIX extensions the tasks will fail if the agent directory has a space in the build path.  An error like the following is thrown
```
C:\Build : The term 'C:\Build' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Build Agent\_work\_tasks\MsixPackaging_e8789f65-a0e2-472b-98ca-8cf ...
```

**To Reproduce**
Use a self hosted Azure DevOps agent, make sure your agent directory has a space in the path i.e. C:\Build Agent\. Make a pipeline that includes an MSIX task such as 'Build and Package'. Run the pipeline and the task will fail.

**Expected behavior**
Task should execute even if space in build agent path.

**Screenshots**
![image](https://user-images.githubusercontent.com/6324102/105974741-1c343600-6086-11eb-8d67-b716151f1c7b.png)

**Comment by lechacon** [comment]
Hi @tomaustin700 . This seems to be due to calling a script with an unquoted path. I believe it was the call to the GetMSBuildPath.ps1 script [here](https://github.com/microsoft/msix-packaging/blob/master/tools/pipelines-tasks/MsixPackaging/msbuild.ts#L77) but I want to confirm. Can you share what was the full content of line 9 in your screenshot?

For now, you may be able to work around this by specifying the full path to MSBuild in the task instead of having it auto-detected. That would skip the call that is causing this error. The path should be similar to "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe".

**Comment by tomaustin700** [comment]
Hi @lechacon, here is the full content of line 9

`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted "C:\Build Agent\_work\_tasks\MsixPackaging_e8789f65-a0e2-472b-98ca-8cfd83ccc3c3\1.0.6\GetMSBuildPath.ps1" -PreferredVersion latest -Architecture x86
`

I will try that workaround for now. Thanks for your help.

**Comment by lechacon** [comment]
This should be fixed now, but not yet published. Will update when it is.

**Comment by lechacon** [comment]
@tomaustin700 Version 1.0.7 of the extension is available now with the fix for this. Could you confirm if it solves your problem and close this issue?

**Comment by tomaustin700** [comment]
Confirmed fixed, thanks @lechacon.
