### ISSUE TITLE
[Feature Request] MSIX Packaging extension for Azure DevOps Release pipelines

### ISSUE THREAD

**Issue by RowlandShaw** [microsoft/msix-packaging#417]
The existing packaging extension combines the build operation into the step. It would be useful to be able to separate these out so that the build pipeline can build, and the release pipeline handles the packaging (and potential onward publishing to store). The idea being to support stages in release pipelines in a side by side manner.

For example, consider an app, that for the sake of this, I'll go with the generic "MyApp" - I want to be able to publish to "insiders" early versions, to garner feedback, before promoting to "general availability". We might want to enable/disable different feature switches, or make other changes that we might currently do as part of the release pipeline prior to packaging and releasing.

This could also be used for other scenarios, such as having a private QA/UAT/etc. version of an app; where there can be assurance that the code that was tested is the code that is then republished into the next environment; or for SaaS scenarios, where an app is customised for different clients as part of the release process (rather than having to maintain separate code branches for each)

**Comment by RowlandShaw** [comment]
This might just be a "how to doc" task, as it appears from https://github.com/microsoft/msix-packaging/blob/master/tools/pipelines-tasks/MsixPackaging/index.ts that it might "just work" if configured correctly in the UI

**Comment by lechacon** [comment]
The MSIX packaging task has two modes for packaging, one builds a solution and the other packages pre-built binaries. The build mode calls MSBuild.exe adding the right parameters for creating a package, so if you want to build without packaging you could use the "MSBuild" or "Visual Studio build" tasks instead. Then, in your release pipeline you can use the MSIX packaging task with the option to only package existing files without building, which would call MakeAppx.exe.

Does that suit your needs?

I imagine the biggest problems would be placing all the files in the right places for publishing them in the build pipeline (as an artifact, I assume) and for building the final package, and that you may be missing anything else that MSBuild does for packaging. But if you really need to use MSBuild.exe for the packaging, then you probably need to re-build anyways since the release pipeline would likely run in a different agent than the build pipeline.

**Comment by samiranshah** [comment]
Closing for now. Please reopen if needed.
