### ISSUE TITLE
[BUG] Windows Sandbox Support

### ISSUE THREAD

**Issue by TanayParikh** [microsoft/msix-packaging#510]
*Project*
MSIX SDK

**Describe the bug**

Wanted to confirm if MSIX installers are supported in the Windows Sandbox environment? We are trying to run a Blazor Hybrid / MAUI app in the Sandbox but get:

![image](https://user-images.githubusercontent.com/14852843/164571120-cb2f39a0-79b7-4b7e-aaa2-153fdcf6f0c9.png)

Related: https://github.com/dotnet/maui/issues/6393

**Comment by lechacon** [comment]
You get that message because the App Installer package is not installed in the sandbox, but that is only the UI for installing with double-click. You can still install MSIX packages in the sandbox with the PowerShell cmdlet Add-AppPackage. You can also install the App Installer package (and its dependencies) with Add-AppPackage, and then you'd be able to install other .msix apps by double-clicking the files.
